name: flask_pipeline

on:
    push:
        branches:
            - main

jobs:
    python_app:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v5
            
            - name: setting up python in your app
              uses: actions/setup-python@v6
              with: 
                python-version: '3.13'

            - name: Installing dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Running the Flask Application
              run: | 
                python app.py &
                sleep 10    

            - name: setting up test cases
              run: | 
                echo "Testing has been Started."
                curl http://127.0.0.1:5000
                echo "Testing has been completed"
              

